
const translations = {
  en: {
    tab_home: "Home",
    tab_commands: "Commands",
    home_title: "Welcome to Maple Raider",
    home_intro: "Maple Raider is a bot to organize MapleStory raids in Discord easily.",
    home_question: "What is Maple Raider?",
    home_answer: "An automated raid organizer bot with language support, buttons, reminders and automatic channels.",
    home_benefits: "5 Benefits of Using a Raid Organizer",
    benefit1: "✅ Avoid confusion in coordination.",
    benefit2: "✅ One-click confirmations.",
    benefit3: "✅ Automatic reminders.",
    benefit4: "✅ Clear organization by boss/date.",
    benefit5: "✅ Private alerts for the leader.",
    invite_button: '<i class="fab fa-discord me-2"></i>Invite to my Server',
    commands_title: "Command Guide",
    boss_command_title: "/boss",
    boss_command_desc: "Creates a new raid. Use this command to specify the boss, difficulty, date, time and max party size.",
    boss_command_params: "Parameters:",
    boss_param_boss: "`boss` – Boss name. Example: Lotus, Damien, Will.",
    boss_param_difficulty: "`difficulty` – Difficulty level. Must be valid for the selected boss.",
    boss_param_date: "`date` – Event date in MM-DD format. Example: `05-30`.",
    boss_param_time: "`time` – Event time in 24-hour format. Example: `22:00`.",
    boss_param_party: "`max_party` – Maximum number of players allowed. Example: `6`.",
    boss_param_description: "`description` – Optional note or message for your team.",
    boss_param_utc_note: "⚠️ Time must be set in UTC, the official timezone used by MapleStory Global servers.",
    boss_command_example: "Example: /boss boss:Lotus difficulty:Hard date:05-30 time:22:00 max_party:6 description:Let's go!",
    bosslist_command_title: "/bosslist",
    bosslist_command_desc: "Displays a list of all confirmed users for the raid.",
    bosscfg_command_title: "/bosscfg",
    bosscfg_command_desc: "Allows server admins to set language, category and permissions.",
    bosshelp_command_title: "/bosshelp",
    bosshelp_command_desc: "Displays this guide directly in Discord for quick reference.",
    bosskick_command_title: "/bosskick",
    bosskick_command_desc: "Allows the organizer to remove a user from the confirmed list of an active raid."


  },
  es: {
    tab_home: "Inicio",
    tab_commands: "Comandos",
    home_title: "Bienvenido a Maple Raider",
    home_intro: "Maple Raider es un bot para organizar raids de MapleStory en Discord.",
    home_question: "¿Qué es Maple Raider?",
    home_answer: "Un bot de organización de raids automatizado con idioma, botones, recordatorios y canales automáticos.",
    home_benefits: "5 ventajas de usar un organizador de raids",
    benefit1: "✅ Sin confusiones al coordinar.",
    benefit2: "✅ Confirmaciones con un clic.",
    benefit3: "✅ Recordatorios automáticos.",
    benefit4: "✅ Organización clara por jefe y fecha.",
    benefit5: "✅ Notificaciones privadas al líder.",
    invite_button: '<i class="fab fa-discord me-2"></i>Invitar a mi Servidor',
    commands_title: "Guía de Comandos",
    boss_command_title: "/boss",
    boss_command_desc: "Crea una nueva raid. Usa este comando para especificar el jefe, dificultad, fecha, hora y el tamaño máximo del grupo.",
    boss_command_params: "Parámetros:",
    boss_param_boss: "`boss` – Nombre del jefe. Ejemplo: Lotus, Damien, Will.",
    boss_param_difficulty: "`difficulty` – Dificultad. Debe ser válida para el jefe seleccionado.",
    boss_param_date: "`date` – Fecha del evento en formato MM-DD. Ejemplo: `05-30`.",
    boss_param_time: "`time` – Hora del evento en formato 24h. Ejemplo: `22:00`.",
    boss_param_party: "`max_party` – Número máximo de participantes. Ejemplo: `6`.",
    boss_param_description: "`description` – Nota o mensaje opcional para tu grupo.",
    boss_param_utc_note: "⚠️ La hora debe estar en horario UTC, que es el horario oficial usado por los servidores de MapleStory Global.",
    boss_command_example: "Ejemplo: /boss boss:Lotus difficulty:Hard date:05-30 time:22:00 max_party:6 description:¡Vamos!",
    bosslist_command_title: "/bosslist",
    bosslist_command_desc: "Muestra una lista de todos los usuarios confirmados para la raid.",
    bosscfg_command_title: "/bosscfg",
    bosscfg_command_desc: "Permite a los admins configurar idioma, categoría y permisos.",
    bosshelp_command_title: "/bosshelp",
    bosshelp_command_desc: "Muestra esta guía directamente en Discord como referencia rápida."
    bosskick_command_title: "/bosskick",
    bosskick_command_desc: "Permite al organizador remover a un usuario de la lista de confirmados de una raid activa."
  }
};
